# -*- coding: utf-8 -*-
"""Tipos de Variáveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjbnAXylwzuH6r_fA1KToyBWinRioyZa

# Tipos de Variáveis em Python

Uma variável é um objeto, afinal tudo é um objeto em Python

int -> inteiro<br>
string -> texto<br>
float -> números com casas decimais (ponto flutuante)<br>
bool ou boolean -> True ou False<br>

Obs: Variáveis em Python não são declaradas explicitamente, mas isso não significa que você deve ficar mudando o tempo todo

Obs2: Cuidado com os nomes restritos (arquivo para Download)
"""

faturamento = 1000
type(faturamento)

faturamento = 1000.00
type(faturamento)

faturamento = '1.000'
type(faturamento)

ganha_bonus = True
type(ganha_bonus)

